spring:
  profiles:
    active: dev
---
server:
  port: 8001
  
spring:
  application:
    name: springcloud-provider-dept
  profiles:
    active: dev

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
server:
  port: 8002
  
spring:
  application:
    name: springcloud-provider-dept
  profiles:
    active: test

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

