spring:
  profiles:
    active: dev
---

server:
  port: 8201
  
spring:
  application:
    name: springcloud-provider-dept-dev
  profiles: dev

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---

server:
  port: 8202
  
spring:
  application:
    name: springcloud-provider-dept-test
  profiles: test

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

